version: "3.7"

services:
  app:
    build: .
    container_name: basis_front
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 8081:8080
    command: [ "yarn", "serve" ]
